---
- name: Serve our file using httpd
  hosts: localhost
  vars:
    ansible_bender:
      base_image: fedora:30
      target_image:
        name: our-httpd
        cmd: httpd -DFOREGROUND
  tasks:
    name: create file 
    file:
    path: /etc/foo.conf
    state: touch
    mode: u+rw,g-wx,o-rwx