# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pip3 install setuptools
          sudo apt install python3.7
          sudo apt install python3-pip
          pip install ansible-bender
          pip3 install ansible-bender
          # Debian Testing/Bullseye or Unstable/Sid
          sudo apt-get -y update
          sudo apt-get -y install podman
          sudo apt-get -y install buildah
          sudo sh -c "printf \"\n$(whoami):100000:65536\n\" >>/etc/subuid"
          sudo sh -c "printf \"\n$(whoami):100000:65536\n\" >>/etc/subgid"
          PATH=$PATH:/home/runner/.local/bin/
          export PATH
          whereis ansible-bender